const assert=require('assert');
const {mergeProgress,stamp}=require('./sync.js');
const base=overrides=>({version:1,settings:{theme:'light'},attempts:[],errors:[],custom:[],custom_deleted:[],daily:{},tasks:{},seen:[],activeExam:null,sync_meta:{updated_at:'2026-01-01T00:00:00.000Z',settings_updated_at:'2026-01-01T00:00:00.000Z'},...overrides});
const attempt=(id,time='2026-01-01T00:00:00.000Z')=>({id,updated_at:time,total:20,correct:10});
assert.equal(stamp(base()).sync_meta.schema_version,1,'local-only state is stamped');
assert.equal(mergeProgress(base({attempts:[attempt('a')]}),base()).attempts.length,1,'empty cloud keeps local progress');
assert.equal(mergeProgress(base(),base({attempts:[attempt('b')]})).attempts.length,1,'empty local receives cloud progress');
let merged=mergeProgress(base({attempts:[attempt('a')]}),base({attempts:[attempt('b')]}));
assert.deepStrictEqual(new Set(merged.attempts.map(x=>x.id)),new Set(['a','b']),'two-device records merge');
merged=mergeProgress(base({attempts:[attempt('same','2026-01-01T00:00:00.000Z')]}),base({attempts:[{...attempt('same','2026-02-01T00:00:00.000Z'),correct:19}]}));
assert.equal(merged.attempts.length,1,'duplicate IDs do not duplicate');assert.equal(merged.attempts[0].correct,19,'newest duplicate wins');
merged=mergeProgress(base({settings:{theme:'dark'},sync_meta:{updated_at:'2026-01-01T00:00:00.000Z',settings_updated_at:'2026-01-01T00:00:00.000Z'}}),base({settings:{theme:'light'},sync_meta:{updated_at:'2026-02-01T00:00:00.000Z',settings_updated_at:'2026-02-01T00:00:00.000Z'}}));
assert.equal(merged.settings.theme,'light','newer settings win');
merged=mergeProgress(base({custom:[{id:'c',title:'old',updated_at:'2026-01-01T00:00:00.000Z'}]}),base({custom:[{id:'c',title:'new',updated_at:'2026-02-01T00:00:00.000Z'}]}));
assert.equal(merged.custom[0].title,'new','newer custom edit wins');
merged=mergeProgress(base({custom:[{id:'c',title:'old',updated_at:'2026-01-01T00:00:00.000Z'}]}),base({custom_deleted:[{id:'c',deleted_at:'2026-02-01T00:00:00.000Z',updated_at:'2026-02-01T00:00:00.000Z'}]}));
assert.equal(merged.custom.length,0,'custom tombstone preserves deletion');
merged=mergeProgress(base({activeExam:{id:'e',updated_at:'2026-01-01T00:00:00.000Z'}}),base({activeExam:{id:'e2',updated_at:'2026-02-01T00:00:00.000Z'}}));
assert.equal(merged.activeExam.id,'e2','newest active exam wins');
merged=mergeProgress(base({version:1}),base({version:2}));assert.equal(merged.version,2,'schema-version mismatch retains newest version');
const syncSource=require('fs').readFileSync('sync.js','utf8');
for(const token of ['DEBOUNCE_MS','addEventListener(\'online\'','setInterval(refresh','Senkronizasyon hatası','signOut'])assert.ok(syncSource.includes(token),`Missing sync behavior: ${token}`);
for(const token of ['auth.getSession()','auth.onAuthStateChange','detectSessionInUrl:true','cleanAuthCallbackUrl','Supabase config loaded','Supabase client created','Initial session found','Initial session missing','Auth event name','Signed-in user email','lastSync?new Intl.DateTimeFormat'])assert.ok(syncSource.includes(token),`Missing auth lifecycle behavior: ${token}`);
console.log('Sync merge, queue, and auth lifecycle tests passed');
