/* Optional Supabase magic-link authentication and deterministic cloud sync. */
(function(global){
  const SCHEMA_VERSION=1, DEBOUNCE_MS=1800, POLL_MS=5*60*1000;
  const now=()=>new Date().toISOString(), clone=value=>JSON.parse(JSON.stringify(value||{}));
  let memoryDeviceId='';const deviceId=()=>{if(typeof localStorage==='undefined'){if(!memoryDeviceId)memoryDeviceId=`device-${Date.now()}-${Math.random().toString(36).slice(2)}`;return memoryDeviceId}let id=localStorage.getItem('lueckenSprintDeviceId');if(!id){id=global.crypto?.randomUUID?.()||`device-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem('lueckenSprintDeviceId',id)}return id};
  const byId=(items=[])=>Object.fromEntries(items.filter(x=>x&&x.id).map(x=>[x.id,x]));
  const newer=(a,b)=>String(a?.updated_at||a?.updatedAt||'')>=String(b?.updated_at||b?.updatedAt||'')?a:b;
  const mergeRecords=(a,b)=>Object.values({...byId(a),...Object.fromEntries(Object.entries(byId(b)).map(([id,row])=>[id,newer(byId(a)[id],row)]))});
  const stamp=state=>{const out=clone(state);out.sync_meta={...(out.sync_meta||{}),schema_version:SCHEMA_VERSION,updated_at:now(),device_id:deviceId(),settings_updated_at:out.sync_meta?.settings_updated_at||now()};return out};
  const mergeProgress=(local,cloud)=>{const l=stamp(local),c=stamp(cloud);const tombstones=mergeRecords(l.custom_deleted||[],c.custom_deleted||[]);const deleted=byId(tombstones);let custom=mergeRecords(l.custom||[],c.custom||[]).filter(item=>!deleted[item.id]||String(deleted[item.id].deleted_at||'')<String(item.updated_at||''));const settings=String(l.sync_meta.settings_updated_at)>=String(c.sync_meta.settings_updated_at)?l.settings:c.settings;const active=newer(l.activeExam&&{...l.activeExam,updated_at:l.activeExam.updated_at||l.sync_meta.updated_at},c.activeExam&&{...c.activeExam,updated_at:c.activeExam.updated_at||c.sync_meta.updated_at});return {...l,version:Math.max(Number(l.version)||1,Number(c.version)||1),settings:clone(settings||{}),attempts:mergeRecords(l.attempts,c.attempts),errors:mergeRecords(l.errors,c.errors),custom,custom_deleted:tombstones,daily:{...(c.daily||{}),...(l.daily||{})},tasks:{...(c.tasks||{}),...(l.tasks||{})},seen:[...new Set([...(c.seen||[]),...(l.seen||[])])],activeExam:active||null,sync_meta:{...l.sync_meta,updated_at:now(),cloud_revision:Math.max(Number(l.sync_meta.cloud_revision)||0,Number(c.sync_meta.cloud_revision)||0)}}};
  const download=(name,data)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  let client=null,getState=()=>({}),replaceState=()=>{},timer=null,applying=false,pending=false,lastSync='',user=null,status='Yerel olarak kaydedildi',message='';
  const publicKey=cfg=>cfg?.publishableKey||cfg?.anonKey||'';
  const configured=()=>{const cfg=global.LUECKENSPRINT_SUPABASE_CONFIG||{};return Boolean(cfg.url&&publicKey(cfg)&&global.supabase?.createClient)};
  const emit=()=>{global.dispatchEvent(new CustomEvent('lueckensprint-sync-status',{detail:{status,message,user,lastSync,pending,configured:configured()}}));mountSettingsPanel()};
  const setStatus=(next,note='')=>{status=next;message=note;emit()};
  const sessionClient=()=>{if(client||!configured())return client;const cfg=global.LUECKENSPRINT_SUPABASE_CONFIG;client=global.supabase.createClient(cfg.url,publicKey(cfg),{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client};
  const fetchCloud=async()=>{const c=sessionClient();if(!c||!user)return null;const {data,error}=await c.from('user_progress').select('*').eq('user_id',user.id).maybeSingle();if(error)throw error;return data};
  const upload=async(force=false)=>{if(!navigator.onLine){setStatus('Çevrimdışı');return}const c=sessionClient();if(!c||!user){setStatus('Yerel olarak kaydedildi');return}if(!pending&&!force)return;setStatus('Senkronize ediliyor');try{const local=stamp(getState());const cloud=await fetchCloud();const merged=cloud?mergeProgress(local,cloud.progress_data):local;applying=true;replaceState(merged);applying=false;const revision=(Number(cloud?.revision)||0)+1;const {error}=await c.from('user_progress').upsert({user_id:user.id,schema_version:SCHEMA_VERSION,progress_data:merged,updated_at:now(),device_id:deviceId(),revision},{onConflict:'user_id'});if(error)throw error;pending=false;lastSync=now();setStatus('Senkronize edildi')}catch(error){applying=false;pending=true;setStatus('Senkronizasyon hatası',error.message||'Tekrar denenecek')}};
  const schedule=()=>{if(applying)return;pending=true;clearTimeout(timer);timer=setTimeout(()=>upload(),DEBOUNCE_MS);setStatus(navigator.onLine?'Senkronize ediliyor':'Çevrimdışı')};
  const refresh=async()=>{const c=sessionClient();if(!c||!user||!navigator.onLine)return;try{setStatus('Senkronize ediliyor');const cloud=await fetchCloud();if(cloud?.progress_data){const merged=mergeProgress(getState(),cloud.progress_data);applying=true;replaceState(merged);applying=false}lastSync=now();setStatus(pending?'Senkronize ediliyor':'Senkronize edildi');if(pending)upload()}catch(error){applying=false;setStatus('Senkronizasyon hatası',error.message||'Tekrar denenecek')}};
  const initialize=async(api)=>{getState=api.getState;replaceState=api.replaceState;sessionClient();if(!client){emit();return}const {data:{session}}=await client.auth.getSession();user=session?.user||null;client.auth.onAuthStateChange((_event,sessionNow)=>{user=sessionNow?.user||null;emit();if(user)firstMerge()});if(user)await refresh();else emit();global.addEventListener('online',()=>{if(pending)upload();else refresh()});global.addEventListener('focus',refresh);document.addEventListener('submit',event=>{if(event.target?.id==='settingsForm'){const state=getState();state.sync_meta={...(state.sync_meta||{}),settings_updated_at:now()}}},true);document.addEventListener('click',event=>{const button=event.target.closest?.('.delete-custom');if(button){const state=getState(),id=button.dataset.id;if(id){state.custom_deleted=state.custom_deleted||[];state.custom_deleted=[...state.custom_deleted.filter(x=>x.id!==id),{id,deleted_at:now(),updated_at:now()}];schedule()}}if(event.target.closest?.('#saveCustomEdit'))setTimeout(()=>{const state=getState();state.custom=(state.custom||[]).map(item=>({...item,updated_at:now()}));schedule()},0)});setInterval(refresh,POLL_MS)};
  const signIn=async(email)=>{const c=sessionClient();if(!c)throw new Error('Supabase yapılandırması eksik.');const redirect=global.location.origin+global.location.pathname;const {error}=await c.auth.signInWithOtp({email,options:{emailRedirectTo:redirect}});if(error)throw error;setStatus('Giriş bağlantısı gönderildi')};
  const signOut=async()=>{if(client)await client.auth.signOut();user=null;setStatus('Yerel olarak kaydedildi')};
  const firstMerge=async()=>{if(!user)return;const cloud=await fetchCloud();const local=getState();if(!cloud&&((local.attempts||[]).length||(local.custom||[]).length)){if(global.confirm('Bu cihazdaki mevcut ilerleme bulut hesabınızla birleştirilsin mi?')){download(`LueckenSprint_ilk_bulut_yedegi_${Date.now()}.json`,local);pending=true;await upload(true)}}else await refresh()};
  const mountSettingsPanel=()=>{let host=document.querySelector('#syncPanelHost');if(!host&&global.VIEW==='settings'){host=document.createElement('div');host.id='syncPanelHost';document.querySelector('#main')?.appendChild(host)}if(!host)return;const email=user?.email||'Misafir mod';host.innerHTML=`<section class="card sync-panel"><h2>Bulut senkronizasyonu</h2><p class="label">${configured()?email:'Supabase yapılandırılmadı — yerel mod aktif.'}</p><p class="sync-status">${status}${message?` · ${message}`:''}</p>${user?`<div class="choice-row"><button class="button" id="syncNow">Şimdi senkronize et</button><button class="button-outline" id="downloadCloud">Bulut verilerimin yedeğini indir</button><button class="button-outline" id="pullCloud">Buluttaki veriyi indir</button><button class="button-outline" id="pushCloud">Yerel veriyi buluta gönder</button><button class="button-danger" id="signOut">Çıkış Yap</button></div>`:`<form id="magicLinkForm" class="choice-row"><input required type="email" id="syncEmail" placeholder="E-posta adresi" aria-label="E-posta adresi"><button class="button">Giriş bağlantısı gönder</button></form>`}</section>`;host.querySelector('#magicLinkForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await signIn(host.querySelector('#syncEmail').value);setStatus('Giriş bağlantısı gönderildi')}catch(error){setStatus('Senkronizasyon hatası',error.message)}});host.querySelector('#syncNow')?.addEventListener('click',()=>upload(true));host.querySelector('#pullCloud')?.addEventListener('click',refresh);host.querySelector('#pushCloud')?.addEventListener('click',()=>{pending=true;upload(true)});host.querySelector('#downloadCloud')?.addEventListener('click',async()=>{try{const row=await fetchCloud();if(row)download(`LueckenSprint_bulut_yedegi_${Date.now()}.json`,row.progress_data)}catch(error){setStatus('Senkronizasyon hatası',error.message)}});host.querySelector('#signOut')?.addEventListener('click',signOut)};
  global.LueckenSync={initialize,onLocalSave:schedule,refresh,upload,signIn,signOut,mountSettingsPanel,firstMerge,mergeProgress,stamp};
  if(typeof module!=='undefined')module.exports={mergeProgress,stamp};
})(typeof window!=='undefined'?window:globalThis);
