import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import cjs from '../app.js';
export const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const schema=JSON.parse(fs.readFileSync(path.join(root,'schemas','linguistic-review.schema.json'),'utf8'));
export const promptVersion='linguistic-review-v1',schemaVersion='1',model=process.env.LINGUISTIC_AUDIT_MODEL||'gpt-5-mini';
export const sha=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
export const readJson=(file,fallback=null)=>fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):fallback;
export const writeJson=(file,value)=>fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n','utf8');
export const corpus=()=>['a1','a2','b1','b2','c1'].flatMap(level=>readJson(path.join(root,'data',`texts-${level}.json`),[]));
export function payload(text){const made=cjs.ctest(text.text,{gaps:20,level:text.level,textId:text.id});return {textId:text.id,level:text.level,title:text.title,topic:text.topic,genre:text.genre,text:text.text,metadata:{numericDifficultyScore:text.numericDifficultyScore,assignedLevel:text.assignedLevel},gaps:made.items.map(item=>({gapId:item.diagnostic.gapId,word:item.word,prefix:item.prefix,completion:item.missing,diagnostic:item.diagnostic}))}}
export const contentHash=text=>sha(JSON.stringify(payload(text))+'|'+promptVersion+'|'+schemaVersion);
export function validateReview(value,expectedId){const required=schema.required;for(const key of required)if(value?.[key]===undefined)throw new Error(`Invalid review: missing ${key}`);if(expectedId&&value.textId!==expectedId)throw new Error('Invalid review: text ID mismatch');for(const key of ['languageNaturalnessScore','coherenceScore','ctestValidityScore'])if(!(Number(value[key])>=0&&Number(value[key])<=100))throw new Error(`Invalid review: ${key}`);for(const key of ['cefrConfidence','overallConfidence'])if(!(Number(value[key])>=0&&Number(value[key])<=1))throw new Error(`Invalid review: ${key}`);if(!['PASS','FIX','QUARANTINE','REJECT'].includes(value.finalDecision))throw new Error('Invalid review: final decision');return value}
export function noPersonalData(input){const string=JSON.stringify(input);if(/@|sb_(?:secret|publishable)|access_token|refresh_token|service_role/i.test(string))throw new Error('Audit payload contains prohibited personal or credential data');return true}
export const blank=(text,decision='PASS',overrides={})=>({textId:text.id,originalLevel:text.level,proposedLevel:text.level,languageNaturalnessScore:92,coherenceScore:92,cefrConfidence:.94,ctestValidityScore:96,overallConfidence:.93,finalDecision:decision,problems:[],proposedCorrections:[],reviewedGapResults:[],reviewerAgreement:'agreement',quarantineReasons:[],reviewModel:'mock-linguistic-reviewer',promptVersion,reviewedAt:new Date().toISOString(),...overrides});
export function decide(a,b,c){const major=[...a.problems,...b.problems,...c.problems].some(problem=>['blocker','critical','major'].includes(problem.severity));const ambiguous=(c.reviewedGapResults||[]).some(gap=>(gap.possibleAlternatives||[]).length||gap.answerIntegrity==='ambiguous');if(c.finalDecision==='REJECT'||major&&c.overallConfidence<.95)return 'REJECT';if(ambiguous||c.finalDecision==='QUARANTINE'||a.cefrConfidence<.75)return 'QUARANTINE';if(c.finalDecision==='FIX'||(c.proposedCorrections||[]).length)return c.overallConfidence>=.95?'FIX':'QUARANTINE';return a.languageNaturalnessScore>=85&&b.ctestValidityScore>=90&&c.overallConfidence>=.9?'PASS':'QUARANTINE'}
export async function apiReview(role,input){if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is required for a real linguistic audit. Set it only in the command environment or GitHub Actions secret.');noPersonalData(input);const prompt=fs.readFileSync(path.join(root,'prompts',`reviewer-${role}.md`),'utf8');const body={model,input:[{role:'system',content:prompt},{role:'user',content:JSON.stringify(input)}],text:{format:{type:'json_schema',name:'linguistic_review',strict:true,schema}}};let last;for(let attempt=0;attempt<3;attempt++){const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){last=new Error(`OpenAI API ${response.status}`);if(response.status===429){await new Promise(resolve=>setTimeout(resolve,1000*(attempt+1)));continue}throw last}const json=await response.json();try{return validateReview(JSON.parse(json.output_text),input.textId)}catch(error){last=error}}throw last||new Error('Malformed review response')}
export function mockReview(role,input){const result=blank({id:input.textId,level:input.level});if(role==='ctest')result.reviewedGapResults=input.gaps.map(gap=>({gapId:gap.gapId,answerIntegrity:'valid',uniqueAnswerConfidence:.98,possibleAlternatives:[],processLevelAssessment:gap.diagnostic.processLevel,proposedProcessLevel:gap.diagnostic.processLevel,strictExamEligible:true,issueReason:null}));return result}
export const stateFile=path.join(root,'linguistic-audit-state.json');
export function reports(results,realAudit=false){const counts={PASS:0,FIX:0,QUARANTINE:0,REJECT:0};for(const result of results)counts[result.finalDecision]++;const summary={generatedAt:new Date().toISOString(),description:'multi-model structured linguistic review',realAudit,model,promptVersion,schemaVersion,totalReviewed:results.length,counts,ambiguousGaps:results.flatMap(result=>result.reviewedGapResults||[]).filter(gap=>(gap.possibleAlternatives||[]).length).length};writeJson(path.join(root,'linguistic-audit-results.json'),results);writeJson(path.join(root,'linguistic-audit-summary.json'),summary);writeJson(path.join(root,'linguistic-fix-proposals.json'),results.filter(result=>result.finalDecision==='FIX'));writeJson(path.join(root,'linguistic-quarantine.json'),results.filter(result=>result.finalDecision==='QUARANTINE'||result.finalDecision==='REJECT'));fs.writeFileSync(path.join(root,'LINGUISTIC_AUDIT_REPORT.md'),`# Linguistic audit\n\nReview type: multi-model structured linguistic review\n\nReal API audit: ${realAudit?'yes':'no'}\n\nReviewed: ${results.length}\n\n- PASS: ${counts.PASS}\n- FIX: ${counts.FIX}\n- QUARANTINE: ${counts.QUARANTINE}\n- REJECT: ${counts.REJECT}\n`);return summary}
